### HTTP Client: REST Client for VS Code, test requests

### Delete all users
POST http://localhost:8080/admin/reset

### Register user
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}

### Login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}

### Update user
PUT http://localhost:8080/api/users
Authorization: Bearer <>
Content-Type: application/json

{
  "email": "walt@breakingbad.com",
  "password": "123456"
}

### make new JWT, Refresh token provided after Bearer
POST http://localhost:8080/api/refresh
Authorization: Bearer <>

### Revoke Refresh token provided after Bearer
POST http://localhost:8080/api/revoke
Authorization: Bearer <>

### Create Pipeline for a specified user by providing JWT that's signed with the userID
POST http://localhost:8080/api/pipelines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJleHByZXNzX3NlcnZlciIsInN1YiI6IjFiOGI1NWI3LTJjOGYtNDI4ZC1iOGQ3LTg0ZjZhN2Q2YzM4ZiIsImlhdCI6MTc3MzY5NTI2MiwiZXhwIjoxNzczNjk4ODYyfQ.tIx36JzOwjKAdpNL36zmdrfsR7aq_lt8hoHXCr_yLTM
Content-Type: application/json

{
    "name": "Cloud Scanner to Discord",
    "actionType": "DATA_MASKING",
    "targetUrls": ["https://discord.com/api/webhooks/12345/abcde"]
}

### List all Pipelines or a specified user by providing JWT that's signed with the userID
GET http://localhost:8080/api/pipelines
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJleHByZXNzX3NlcnZlciIsInN1YiI6IjFiOGI1NWI3LTJjOGYtNDI4ZC1iOGQ3LTg0ZjZhN2Q2YzM4ZiIsImlhdCI6MTc3MzY5NTI2MiwiZXhwIjoxNzczNjk4ODYyfQ.tIx36JzOwjKAdpNL36zmdrfsR7aq_lt8hoHXCr_yLTM

### enqueue job
POST http://localhost:8080/api/webhooks/wh_fc6c8ebe0500c139
Content-Type: application/json

{
  "topic": "Currency",
  "event": "Transform Dollars to Euros"
}